"""Add is_active column to Patient

Revision ID: 03261aaa69e8
Revises: 438250dbc705
Create Date: 2024-06-17 03:34:07.455769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03261aaa69e8'
down_revision = '438250dbc705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
