"""empty message

Revision ID: 438250dbc705
Revises: 3cf8654c7367
Create Date: 2024-06-17 01:58:07.850921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '438250dbc705'
down_revision = '3cf8654c7367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('date_of_admission',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.drop_constraint('vital_signs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('vital_signs_ibfk_1', 'patient', ['patient_id'], ['id'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('date_of_admission',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
